apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: gruppe1
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: frontend