apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: gruppe1
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: testfront
        image: brianstjernholm/frontend:4
        #imagePullPolicy: IfNotPresent
        # env:
        # - name: DBHOST
        #   value: 10.101.183.170
        ports:
        - containerPort: 80
          protocol: TCP