apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: gruppe1
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: testback
        image: brianstjernholm/backend:7
        # env:
        # - name: DBHOST
        #   value: 10.101.183.170
        ports:
        - containerPort: 80