apiVersion: v1
kind: Service
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: backend-deployment