apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: gruppe1
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: backend