apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: gruppe1
  labels:
    app: mysqldb
spec:
  selector:
    app: mysqldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306