apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: gruppe1
  labels:
    app: mysqldb
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - name: mysqldb
        image: mysql:8.0.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            cpu: 10m
            memory: 0.2Gi
          requests:
            cpu: 10m
            memory: 0.2Gi
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
